# Generated by Django 5.2.3 on 2025-07-04 07:39

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_myself', models.CharField(max_length=500, verbose_name='О себе')),
                ('photo', models.ImageField(upload_to=account.models.path_to_user_directory, verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('l_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('registration_time', models.DateTimeField(auto_now_add=True, verbose_name='Время регистрации')),
            ],
        ),
    ]
