# Generated by Django 5.2.3 on 2025-09-07 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sex', models.CharField()),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('about', models.CharField(blank=True, max_length=250, verbose_name='О себе')),
                ('photos', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('profile_photo', models.ImageField(blank=True, upload_to='', verbose_name='Фото профиля')),
                ('i_search', models.CharField(verbose_name='Я ищу')),
                ('auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
