# Generated by Django 5.2.3 on 2025-11-06 00:51

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.Profile.user_photo_path, verbose_name='Фото профиля'),
        ),
    ]
