# Generated by Django 5.2.3 on 2025-08-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
