# Generated by Django 5.2.3 on 2025-08-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userlist_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userlist',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
