# Generated by Django 5.2.3 on 2025-11-16 22:02

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='', upload_to=account.models.Profile.user_photo_path, verbose_name='Фото профиля'),
        ),
    ]
