# Generated by Django 5.2.3 on 2025-11-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2025-11-23'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userauth',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
