# Generated by Django 5.2.3 on 2025-08-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userlist_is_active_userlist_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
