"""
Django settings for pet_project project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import sys
from datetime import timedelta

from pathlib import Path
from dotenv import load_dotenv


path_to_conf_env = f'{Path(__file__).resolve().parent}/.env'
load_dotenv(verbose=True, dotenv_path=path_to_conf_env)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('ENV_SECRET_KEY', os.environ.get('CONF_SECRET_KEY'))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework_simplejwt',
    'rest_framework',
    'account',
    'main',
    'captcha',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pet_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pet_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': os.environ.get('ENV_DATABASES_ENGINE', os.environ.get('DATABASES_ENGINE')),
        'NAME': os.environ.get('ENV_DATABASES_NAME', os.environ.get('DATABASES_NAME')),
        'USER': os.environ.get('ENV_DATABASES_USER', os.environ.get('DATABASES_USER')),
        'PASSWORD': os.environ.get('ENV_DATABASES_PASSWORD', os.environ.get('DATABASES_PASSWORD')),
        'HOST': os.environ.get('ENV_DATABASES_HOST', os.environ.get('DATABASES_HOST')),
        'PORT': os.environ.get('ENV_DATABASES_PORT', os.environ.get('DATABASES_PORT'))
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = []

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# аутентификация

AUTH_USER_MODEL = 'account.UserAuth'

AUTHENTICATION_BACKENDS = [
    "account.authentication.EmailAuthBackend",
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ]
}

# --------------------------- JWT / TOKEN ---------------------------
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "ON_LOGIN_SUCCESS": "rest_framework_simplejwt.serializers.default_on_login_success",
    "ON_LOGIN_FAILED": "rest_framework_simplejwt.serializers.default_on_login_failed",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),

    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}


# --------------------------------- CAPTCHA -------------------------------------
CAPTCHA_LENGTH = 4  # Количество символов в капче.
CAPTCHA_FONT_SIZE = 28  # Размер шрифта.
CAPTCHA_BACKGROUND_COLOR = '#1B083F'  # Цвет фона.
CAPTCHA_FOREGROUND_COLOR = '#FFFFFF'  # Цвет текста.
CAPTCHA_TIMEOUT = 5  # Время в минутах, через которое капча становится недействительной.

CAPTCHA_NOISE_FUNCTIONS = ('captcha.helpers.noise_arcs',)
# определяет, какие функции "шума" будут применяться к изображению капчи
#     'captcha.helpers.noise_arcs', <--- Добавляет дуги
#     'captcha.helpers.noise_dots', <--- Добавляет точки
#     'captcha.helpers.noise_null', <--- Без шума>


# ------------------------------- Логирование -----------------------------------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            # Указываем, что хэндлер должен писать в stdout
            'stream': sys.stdout,
        },
    },
    'root': {
        'handlers': ['console'],  # Это можно использовать для захвата ВСЕХ логов
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',  # Или 'DEBUG' для более подробных логов
            'propagate': False,
        },
    },
}

# ------------------------- REDIS ------ CELERY ------ RABBITMQ -------------------------

get_rabbitmq_user = os.environ.get('ENV_RABBITMQ_USER', os.environ.get('RABBITMQ_USER'))
get_rabbitmq_password = os.environ.get('ENV_RABBITMQ_PASSWORD', os.environ.get('RABBITMQ_PASSWORD'))
get_redis_password = os.environ.get('ENV_REDIS_PASSWORD', os.environ.get('REDIS_PASSWORD'))

CELERY_BROKER_URL = f'pyamqp://{get_rabbitmq_user}:{get_rabbitmq_password}@rabbitmq:5672//'

# Бэкенд для хранения результатов выполнения задач
CELERY_RESULT_BACKEND = f"redis://:{get_redis_password}@redis:6379/0"

# Формат сериализации данных
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://:{get_redis_password}@redis:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 100},
        }
    }
}
