# Generated by Django 5.2.3 on 2025-08-07 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('l_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('sex', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')])),
                ('about_me', models.TextField(blank=True, max_length=250, verbose_name='о себе')),
                ('search', models.CharField(choices=[('М', 'Парня'), ('Ж', 'Девушку')])),
                ('relationship_goal', models.CharField(max_length=250, verbose_name='Цель отношений')),
                ('slug', models.SlugField(unique=True)),
                ('UserID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.userlist')),
            ],
        ),
    ]
